### PR TITLE
Luke gls

### PR DESCRIPTION
**Pull request by lukeers**
Adding compatibility and more generalization for the code to work with UW-IRAL dataset, added more command line arguments for the location of visual features, and file that stores list of instances/images. All arguments are by default the original hardcoded ones, thus preserving all previous scripts ability to remain running the same scripts as before.

### CODE REVIEW

**Comment by fmof** [comment]
Do you have an example command to run for your experiments?

**Comment by lukeers** [comment]
python2 cLL-ML.py --resDir ../Results --cat object --pre conf_files/UW_english/UW_AMT_description_documents_per_image_nopreproc_stop_raw.conf --cutoff 0.25 --seed 25 --visfeat UW_ImgDzPerImage --listof list_of_images.conf 
[UW_ImgDzPerImage.zip](https://github.com/iral-lab/GLS/files/3239390/UW_ImgDzPerImage.zip)
here is the dataset for my visual features

**Comment by fmof** [comment]
Luke what is the portion of this command that makes it per-image rather than per-instance?

**Comment by fmof** [comment]
@nispillai can you please run both Caroline's and Luke's commands and verify?

**Comment by lukeers** [comment]
`--visfeat UW_ImgDzPerImage --listof list_of_images.conf`
The visual feature folder structure is by image rather than instance & the -listof takes in a list of images rather than the usual list of instances

**Comment by nispillai** [comment]
Sure. I will try both the commands.

**Comment by fmof** [comment]
Any update on this? Also Luke, are your example commands written down in a file? (If not, please add one.)

**Comment by nispillai** [comment]
I am contacting Luke for the image dataset and other parameter files. Will
update once I run.

**Comment by lukeers** [comment]
Frank, I am adding a file that runs my experiment

**Comment by nispillai** [comment]
Execution with images got finished successfully. But having issues
executing the script for every instance[checking with Luke about the
issue].

Command I successfully executed:
python cLL-ML.py --resDir UW_raw_75_3 --pre
conf_files/UW_english/UW_AMT_description_documents_per_image_nopreproc_stop_raw.conf
--cat object --cutoff 0.75 --visfeat UW_ImgDzPerImage --listof
list_of_images.conf --seed 1234

**Comment by nispillai** [comment]
Update as of now:

1. Caroline's check-in[main branch]:
Verified Caroline's checkin [main branch] and updated results to
'testResults' folder.  All executions were successful.
Commands that I executed:

 python cLL-ML.py --resDir testing_english --pre
conf_files/english/english_raw.conf --cat rgb --seed 123456789
 python cLL-ML.py --resDir testing_english_stem --pre
conf_files/english/english_stemmed.conf --cat rgb --seed 123456789
 python cLL-ML.py --resDir testing_hindi --pre
conf_files/hindi/hindi_main_excluded_workers_raw.conf --cat rgb --seed
123456789
 python cLL-ML.py --resDir testing_hindi_stem --pre
conf_files/hindi/hindi_main_excluded_workers_stemmed.conf --seed
123456789 --cat all
 python cLL-ML.py --resDir testing_spanish --pre
conf_files/spanish/sp_3batches_lowinst_raw.conf --seed 123456789 --cat
all


2. Luke's check-in [Luke_GLS branch]:
Verified the execution with option '--listof list_of_images.conf' and it
was successful. This option would test the script for every image.
--> python cLL-ML.py --resDir UW_raw_75_3 --pre
conf_files/UW_english/UW_AMT_description_documents_per_image_nopreproc_stop_raw.conf
--cat object --cutoff 0.75 --visfeat UW_ImgDzPerImage --listof
list_of_images.conf --seed 1234

Issues:

I could not successfully run Luke's checkin without '--listof' option. This
execution is intended to learn and produce results for every instance.
--> Issue could be w.r.t my setting. I am contacting Luke to rectify the
issue.

**Comment by lukeers** [comment]
Nisha, my dataset currently is not formatted to process by instance since we are processing by image. I made sure to make it compatible with by-instance methods but there will be an error when attempting to run my data as by-instance.

**Comment by fmof** [comment]
What's the current status of this PR?

**Comment by lukeers** [comment]
Nisha has confirmed via email that the code successfully ran and had the expected output

**Comment by fmof** [comment]
So it's good to merge?

**Comment by lukeers** [comment]
Yes, I just removed a group of result files I had accidentally pushed. Should be good to go now!

**Pull request merged**
